### ISSUE TITLE
Auto Test Connection

### ISSUE THREAD

**Issue by bkcaudil** [dcryans-dynatrace/Dynatrace-Config-Manager#58]
If there is an issue with connectivity or a problem with the token the UI page gets stuck trying over and over. Even hitting OK doesn't make the window with error go away.  Eventually you can get it past it. But if you need to Add a Proxy or change URL it get's stuck testing over and over. I would like to see the test connection option come back, or at least after initial test a re-try button. Otherwise you get stuck in the loop of it auto testing.

**Comment by dcryans** [comment]
sorry about that, and about my slow response time
I will work on fixing it ASAP

**Comment by dcryans** [comment]
Fixed with v0.16.3
https://github.com/dcryans-dynatrace/Dynatrace-Config-Manager/releases/latest
